name: CI

on: [push]

jobs:
  build:
    name: Test
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build SwiftySlack
      run: swift build
    - name: Run tests
      run: swift test
