name: CI

on: [push]

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build SwiftySlack for ${{ matrix.os }}
      run: swift build
    - name: Run tests on ${{ matrix.os }}
      run: swift test
